### ISSUE TITLE
Titre de dossier incorrect - Horizon_XI_FR_Project

### ISSUE THREAD

**Issue by zoliaaz** [AlexandreCA/Traduction-fran-aise-du-client-FFXI#6]
Bonjour,

Lorsqu'on utilise le Github desktop, le nom du dossier " Horizon_XI_FR_Project" crée une erreur car il y un espace au début, avant le H. Sur mon fork j'ai du le renommer.

Vu que tu as rajouter des nouveaux fichiers dans ton dossiers, si je veux le synchroniser, car créer un autre dossier. 

Peux tu retirer l'espace avant le H? 

Merci d'avance.

**Comment by AlexandreCA** [comment]
Bonjour,

Je ne vois pas d’espace au début du H d’Horizon. Sous Windows, Github refuse de cloner mon repertoire, mais c’est OK sous mon MacOS. Je tente de corriger le problème.

De : zoliaaz ***@***.***>
Date : mardi, 13 août 2024 à 14:47
À : AlexandreCA/Traduction-fran-aise-du-client-FFXI ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [AlexandreCA/Traduction-fran-aise-du-client-FFXI] Titre de dossier incorrect - Horizon_XI_FR_Project (Issue #6)

Bonjour,

Lorsqu'on utilise le Github desktop, le nom du dossier " Horizon_XI_FR_Project" crée une erreur car il y un espace au début, avant le H. Sur mon fork j'ai du le renommer.

Vu que tu as rajouter des nouveaux fichiers dans ton dossiers, si je veux le synchroniser, car créer un autre dossier.

Peux tu retirer l'espace avant le H?

Merci d'avance.

**Comment by AlexandreCA** [comment]
Essaye a nouveau. Le probleme a l'air corrigé de mon coté.

**Comment by zoliaaz** [comment]
Merci, ça a fonctionné.
